---
- name: Deploy Docker Container
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull the Docker image
      community.docker.docker_image:
        name: "zarifa003/ansibletask:0.0.1"
        source: pull

    - name: Run the Docker container
      community.docker.docker_container:
        name: "my_ansibletask_app"
        image: "zarifa003/ansibletask:0.0.1"
        state: started


