---
- name: Deploy Docker Container
  hosts: ec2_instances
  become: yes
  gather_facts: yes  # Gather facts to identify the Python interpreter

  tasks:
    - name: Install pip3
      become: yes
      dnf:
        name: python3-pip
        state: present

    - name: Install Docker Python Library
      pip:
        name: docker

    - name: Pull the Docker image
      community.docker.docker_image:
        name: "zarifa003/ansibletask:0.0.1"
        source: pull

    - name: Run the Docker container
      community.docker.docker_container:
        name: "my_ansibletask_app"
        image: "zarifa003/ansibletask:0.0.1"
        state: started
