---
- name: Install Node.js on EC2 Instance
  hosts: ec2_instances
  become: true
  tasks:
    - name: Install Node.js
      shell: |
        curl -sL https://rpm.nodesource.com/setup_14.x | bash -
        yum install -y nodejs

